@node mudcore.args
@section mudcore.args

The @code{mudcore.args} table holds the command-line args passed to the
mudcore binary. Any flags (@code{-foo} or @code{-no-foo}) are mapped so
@code{mudcore.args['foo']} evaluates to @code{true} or
@code{false}. Options (@code{-foo=bar}) are mapped so
@code{mudcore.args['foo'] == 'bar'}.  Positional arguments are indexed
by integers.

Given the following lua code:
@example
for k, v in pairs(mudcore.args) do print(k, v) end
@end example

Running mudcore as @code{mudcore -foo -no-bar -baz=quux -- -one two
three} will print:

@example
1       -one
2       two
3       three
bar     false
foo     true
baz     quux
@end example

Note the use of @code{--} to signal the end of options, causing
@code{-one} to be interpreted as the first positional argument. If
@code{--} doesn't appear on the command-line, the first non-option
non-flag argument is considered the start of positional arguments.
